import { useEffect, useState, type ReactNode } from 'react'
import { BarChart3, Bell, Bot, Building2, ChevronRight, MessageSquare, Users } from 'lucide-react'
import './App.css'

type AdminDashboardProps = { onOpen: (view: string) => void }
type Summary = { collectionsToday: number; completedCollections: number; activeHouseholds: number; pendingPayments: number; companiesTotal: number; companiesApproved: number; companiesPending: number; companiesCancelled: number; pendingCompanyRecords: Array<{ id: string; name: string; location: string }> }
const apiBase = import.meta.env.VITE_API_URL ?? 'http://localhost:5000'

export default function AdminDashboard({ onOpen }: AdminDashboardProps) {
  const [summary, setSummary] = useState<Summary | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { void fetch(`${apiBase}/api/dashboard/summary`).then(async (response) => { const result = await response.json() as Summary | { error?: string }; if (!response.ok) throw new Error('error' in result ? result.error : 'Dashboard data could not be loaded'); setSummary(result as Summary) }).catch((requestError: unknown) => setError(requestError instanceof Error ? requestError.message : 'Dashboard data could not be loaded')) }, [])
  const value = (number: number | undefined): number | string => number ?? '...'
  return <><div className="admin-heading"><div><p className="section-kicker"><span className="kicker-line" /> SYSTEM ADMINISTRATION</p><h1>Platform dashboard</h1><p>Live platform records from the EcoRoute database.</p></div><span className="admin-status"><i /> Database connected</span></div>{error && <p className="settings-error company-error">{error}</p>}<section className="admin-metrics"><AdminMetric icon={<Building2 />} label="Registered companies" value={value(summary?.companiesTotal)} tone="green" /><AdminMetric icon={<Users />} label="Active households" value={value(summary?.activeHouseholds)} tone="blue" /><AdminMetric icon={<BarChart3 />} label="Collections recorded" value={value(summary?.collectionsToday)} tone="yellow" /><AdminMetric icon={<MessageSquare />} label="Pending payments" value={value(summary?.pendingPayments)} tone="coral" /></section><section className="admin-grid"><article className="admin-panel"><div className="admin-panel-heading"><div><h2>Company approvals</h2><p>Pending records from the database</p></div><button onClick={() => onOpen('Companies')}>View all <ChevronRight size={14} /></button></div>{summary?.pendingCompanyRecords.length ? summary.pendingCompanyRecords.map((company) => <div className="approval-row" key={company.id}><span className="company-symbol"><Building2 size={15} /></span><div><strong>{company.name}</strong><small>{company.id} · {company.location}</small></div><span className="pending-tag">Pending</span></div>) : <p className="company-loading">{summary ? 'No pending company approvals.' : 'Loading approvals...'}</p>}<button className="admin-action" onClick={() => onOpen('Companies')}>Review applications <ChevronRight size={14} /></button></article><article className="admin-panel activity-panel"><div className="admin-panel-heading"><div><h2>Company status</h2><p>Current database totals</p></div><Bell size={17} /></div><div className="activity-row"><span className="activity-dot green" /><div><strong>{value(summary?.companiesApproved)} approved companies</strong><small>Active collection companies</small></div></div><div className="activity-row"><span className="activity-dot yellow" /><div><strong>{value(summary?.companiesPending)} pending approvals</strong><small>Require administrator review</small></div></div><div className="activity-row"><span className="activity-dot blue" /><div><strong>{value(summary?.companiesCancelled)} cancelled companies</strong><small>Inactive platform accounts</small></div></div></article></section><section className="admin-ai"><div className="admin-ai-icon"><Bot size={21} /></div><div><h2>EcoRoute AI Assistant</h2><p>Ask for platform reports using verified records from the database.</p></div><button onClick={() => onOpen('AI Assistant')}>Open assistant <ChevronRight size={15} /></button></section></>
}
function AdminMetric({ icon, label, value, tone }: { icon: ReactNode; label: string; value: number | string; tone: string }) { return <div className={`admin-metric ${tone}`}><span>{icon}</span><small>{label}</small><strong>{value}</strong><em>Live database record</em></div> }
